### ISSUE TITLE
make: zeromq install error 1

### ISSUE THREAD

**Issue by spmn45** [Perlover/bitcoin-kit-makefile#1]
$make i-want-lightning |& tee -a my_make_output.txt
cd external/libzmq && { \
	./autogen.sh && ./configure --prefix=/home/admin LDFLAGS="-L/home/admin/lib -L/home/admin/lib64 -L/usr/local/lib64 -L/lib64 -L/usr/lib64" CPPFLAGS="-I/home/admin/include" && make  && make install && echo "ZeroMQ was installed - OK"; \
} &> make_out.txt && tail make_out.txt
mk/zeromq.mk:4: recipe for target 'zeromq_install' failed
make: *** [zeromq_install] Error 1

**Comment by spmn45** [comment]
I'm installing onto a computer with SSD that already has bitcoin core

**Comment by spmn45** [comment]
git pull
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 7 (delta 5), reused 7 (delta 5), pack-reused 0
Unpacking objects: 100% (7/7), done.
From https://github.com/Perlover/bitcoin-kit-makefile
   2b38b18..b794a15  master     -> origin/master
Updating 2b38b18..b794a15
Fast-forward
 CHANGES.txt  | 3 +++
 mk/common.mk | 2 +-
 2 files changed, 4 insertions(+), 1 deletion(-)
admin@SavageLND-desktop:~/bitcoin-kit-makefile$ make i-want-lightning
cd external/libzmq && { \
	./autogen.sh && ./configure --prefix=/home/admin LDFLAGS="-L/home/admin/lib -L/home/admin/lib64 -L/usr/local/lib64 -L/lib64 -L/usr/lib64" CPPFLAGS="-I/home/admin/include" && make  && make install && echo "ZeroMQ was installed - OK"; \
} &> make_out.txt && tail make_out.txt
mk/zeromq.mk:4: recipe for target 'zeromq_install' failed
make: *** [zeromq_install] Error 1

**Comment by spmn45** [comment]
could it be wrong directory path? These are my directories:
bin   cdrom  dev  home        initrd.img.old  lib64       media  opt   root  sbin  srv       sys  usr  vmlinuz
boot  core   etc  initrd.img  lib             lost+found  mnt    proc  run   snap  swapfile  tmp  var  vmlinuz.old

**Comment by spmn45** [comment]
I have no directory called 'external"

**Comment by spmn45** [comment]
I did find 'external'. No such file or directory

**Comment by spmn45** [comment]
Running Ubuntu 16.04.5 Xenial. Does this only work for CentOS?

**Comment by Perlover** [comment]
> I'm installing onto a computer with SSD that already has bitcoin core

My makefile has been written to compile the bitcoind & lnd from sources. I cannot guarantee result if you don't follow the instructions. But you can follow the instruction, to get bitcoind & lnd in `bitcoin` home user directory for example and after to change the LND settings to your bitcoind daemon. But there may be other pitfalls - for example you will need to change startup scripts in $HOME/bin

**Comment by Perlover** [comment]
> Does this only work for CentOS?

I tested in Linux Mint 18.3 (it's Ubuntu 16.04 based OS) and in CentOS 6.\*

But it's work only if you follow to instructions are described in README file. For example my script will compile GCC 7.*, Autoconf tools, fresh GIT version (to be needed for Golang build system), libraries and many other tools and compilers (Golang, Node.JS (for lncli-web for example or for ln-rebalance utility in future), Python 3 - all these to be compiled from sources in $HOME directory) in $HOME directory. All compilers and libraries are located in $HOME directory and linked with paths from $HOME. I used this makefile to isolate any system files from bitcoin related tools + compilers and etc.

**Comment by Perlover** [comment]
> I did find 'external'. No such file or directory

cd ~/bitcoin-kit-makefile/external/

**Comment by Perlover** [comment]
@spmn45 , did you resolve this problem?
I want to close this first ticket :)

**Comment by spmn45** [comment]
Yes thank you so much! Have a great day!!

On Feb 6, 2019, at 10:20 AM, Perlover <notifications@github.com<mailto:notifications@github.com>> wrote:


@spmn45<https://github.com/spmn45> , did you resolve this problem?
I want to close this first ticket :)

**Comment by Perlover** [comment]
Today i tested installation and i found bug in installation process
If you had some problems during installation and have unfinished installation you can try for finish:

    cd ~/bitcoin-kit-makefile/
    git pull
    make i-want-lightning |& tee -a my_make_output.txt
    make set-up-lightning-mainnet
